// <auto-generated />
namespace FindIt.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addingcontactindex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingcontactindex));
        
        string IMigrationMetadata.Id
        {
            get { return "201309200153052_adding-contact-index"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
